server:
    host: 0.0.0.0
    port: 80
singbox:
    bin_path: /usr/bin/sing-box
    config_dir: /root/github.com/firadio/golang-singbox-manager/configs/singbox
    log_dir: /root/github.com/firadio/golang-singbox-manager/logs/singbox
database:
    path: /root/github.com/firadio/golang-singbox-manager/data/manager.db
logging:
    level: info
    format: text
auth:
    enabled: true
    password: "123"
mikrotik:
    enabled: true
    address: 192.168.30.254
    username: tt
    password: 123qwe
    port: 65428
    routing_table: rtab-250
